### ISSUE TITLE
nose

### ISSUE THREAD

**Issue by RainerShad1** [GNR092/DDTank-Energy-Stone-Calculator#3]
nose ocmo funciona como lo activo o que?

**Comment by GNR092** [comment]
solo descarga [v1.0.8](https://github.com/GNR092/DDTank-Energy-Stone-Calculator/releases/tag/V1.0.8) y pruebala o que problema tienes?

**Comment by RainerShad1** [comment]
> solo descarga [v1.0.8](https://github.com/GNR092/DDTank-Energy-Stone-Calculator/releases/tag/V1.0.8) y pruebala o que problema tienes?

osea como abro el programa?

**Comment by RainerShad1** [comment]
ah ya se como abrirlo esque no lo habia visto bien

**Comment by RainerShad1** [comment]
ya la probe y esta muy buena gracias por crear este programa muy util
